---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: "checking.........!"
    file:
      path: deploy.py
      mode: 'u+x'
  - name: "Deploying the network. please wait patiently!"
    command:
      ./deploy.py
  #- name: Set ANSIBLE_HOST_KEY_CHECKING to False
  #  set_fact:
  #    ansible_env:
  #      ANSIBLE_HOST_KEY_CHECKING: False
  #- name: Extract Bastion public IP
  #  set_fact:
  #    bastion_public_ip: "{{ hostvars[item].ansible_host }}"
  #  when: item in groups['Bastion']
  #  loop: "{{ groups['Bastion'] }}"

  #- name: Extract webserver private IPs
  #  set_fact:
  #    webserver_private_ips: "{{ groups['webservers'] | map('extract', hostvars, 'ansible_host') | list }}"

  #- name: Display extracted IPs
  #  debug:
  #    msg: "Bastion IP: {{ bastion_public_ip }}, Webserver IPs: {{ webserver_private_ips }}"
  #- name: SSH into the node
  #  command: >
  #    ssh -i private-key -o ProxyCommand="ssh -i private-key -W %h:%p ubuntu@{{ bastion_public_ip }}" ubuntu@{{ item }}
  #  loop: "{{ webserver_private_ips }}"
- hosts: webservers
  gather_facts: yes
- hosts: HAproxy
  gather_facts: yes
  become: yes
  become_method: sudo
  tasks:
  
  - name: "System Update"
    apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 7200
      force_apt_get: true

  - name: "installing NGinx"
    apt:
      name: nginx 
      state: latest
      force_apt_get: yes
  - name: "configuring TCP and UDP"
    template:
        src: "./nginx.j2"
        dest: "/etc/nginx/nginx.conf"
  - name: "restarting nginx"
    service:
       name: nginx
       state: restarted
- hosts: webservers
  gather_facts: yes
  become: yes
  become_method: sudo

  tasks:
  - name: "system update"
    apt:
      update_cache: true
      cache_valid_time: 7200
      force_apt_get: true
  - name: "installing pip3"
    apt:
      name: python3-pip
  
  - name: "installing gunicorn"
    apt:
      name: gunicorn
  - name: "inastalling flask"
    apt:
      name: python3-flask
  - name: "installing snmpd"
    apt:
      name: snmpd
      state: latest
  - name: "configuring snmpd"
    template:
      src: "./snmpd.conf"
      dest: "/etc/snmp/snmpd.conf"
  - name: "restarting snmpd"
    service:
      name: snmpd
      state: restarted
      enabled: yes
  - name: "copying service.py"
    copy:
     src: service.py
     dest: /home/ubuntu/service.py
     owner: ubuntu
     mode: 0644
  - name: "running flask app"
    shell: gunicorn -w 2 -D -b 0.0.0.0:5000 service:app
  