---
#- hosts: webservers
 # gather_facts: yes
- hosts: HAproxy
  gather_facts: yes
  become: yes
  become_method: sudo

  tasks:
  - name: "System Update"
    apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 7200
      force_apt_get: true

  - name: "installing NGinx"
    apt:
      name: nginx 
      state: latest
      force_apt_get: yes