---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: "checking.........!"
    file:
      path: opp.py
      mode: 'u+x'
  - name: "Working on updates!"
    command:
       ./opp.py
  - name: Wait for a specific duration
    pause:
      seconds: 30
- hosts: webservers
  vars:
    ansible_ssh_common_args: '-F ./ssh_config'
  gather_facts: yes
- hosts: HAproxy
  vars:
    ansible_ssh_common_args: '-F ./ssh_config'
  gather_facts: yes
  become: yes
  become_method: sudo

  tasks:
  - name: "configuring TCP and UDP"
    template:
        src: "./nginx.j2"
        dest: "/etc/nginx/nginx.conf"
  - name: "restarting nginx"
    service:
       name: nginx
       state: restarted
- hosts: webservers
  gather_facts: yes
  become: yes
  become_method: sudo

  tasks:
  - name: "system update"
    apt:
      update_cache: true
      cache_valid_time: 7200
      force_apt_get: true
  - name: "installing pip3"
    apt:
      name: python3-pip
  
  - name: "installing gunicorn"
    apt:
      name: gunicorn
  - name: "inastalling flask"
    apt:
      name: python3-flask
  - name: "installing snmpd"
    apt:
      name: snmpd
      state: latest
  - name: "configuring snmpd"
    template:
      src: "./snmpd.conf"
      dest: "/etc/snmp/snmpd.conf"
  - name: "restarting snmpd"
    service:
      name: snmpd
      state: restarted
      enabled: yes
  - name: "copying service.py"
    copy:
     src: service.py
     dest: /home/ubuntu/service.py
     owner: ubuntu
     mode: 0644
  - name: "running flask app"
    shell: gunicorn -w 2 -D -b 0.0.0.0:5000 service:app
  